// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZSJR66k2XZw0LShZIA32fIfE9TOur0JU',
    appId: '1:747621038326:web:7f078fd93acf5bcfbc54d7',
    messagingSenderId: '747621038326',
    projectId: 'do-an-tot-nghiep-afd66',
    authDomain: 'do-an-tot-nghiep-afd66.firebaseapp.com',
    databaseURL: 'https://do-an-tot-nghiep-afd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'do-an-tot-nghiep-afd66.appspot.com',
    measurementId: 'G-1BQ20ZR67E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2HL_bs0--wz0s-097QEHkCAgERYwt8U',
    appId: '1:747621038326:android:308c1760d53ec353bc54d7',
    messagingSenderId: '747621038326',
    projectId: 'do-an-tot-nghiep-afd66',
    databaseURL: 'https://do-an-tot-nghiep-afd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'do-an-tot-nghiep-afd66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfiD-rGOTiWtTYSzjR2I4ofYGkrglqZY',
    appId: '1:747621038326:ios:b7b4c0bf398e759abc54d7',
    messagingSenderId: '747621038326',
    projectId: 'do-an-tot-nghiep-afd66',
    databaseURL: 'https://do-an-tot-nghiep-afd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'do-an-tot-nghiep-afd66.appspot.com',
    iosBundleId: 'com.example.doAnTotNghiep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfiD-rGOTiWtTYSzjR2I4ofYGkrglqZY',
    appId: '1:747621038326:ios:b7b4c0bf398e759abc54d7',
    messagingSenderId: '747621038326',
    projectId: 'do-an-tot-nghiep-afd66',
    databaseURL: 'https://do-an-tot-nghiep-afd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'do-an-tot-nghiep-afd66.appspot.com',
    iosBundleId: 'com.example.doAnTotNghiep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZSJR66k2XZw0LShZIA32fIfE9TOur0JU',
    appId: '1:747621038326:web:500b61ff71e44ffcbc54d7',
    messagingSenderId: '747621038326',
    projectId: 'do-an-tot-nghiep-afd66',
    authDomain: 'do-an-tot-nghiep-afd66.firebaseapp.com',
    databaseURL: 'https://do-an-tot-nghiep-afd66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'do-an-tot-nghiep-afd66.appspot.com',
    measurementId: 'G-6Y1Z8R4T15',
  );
}
